---
- name: roles
  hosts: node[1:2].example.com
  user: ansible
  become: yes
  become_method: sudo
  become_user: root
  
  roles:
  - role: install_httpd
    fw_service_to_open_2: https
  - role: install_vsftpd
  

  
...