---
# tasks file for install_vsftpd
- name: install vsftpd
  dnf:
    name: vsftpd
    state: latest

- name: fw open vsftpd
  firewalld:
    service: ftp
    permanent: yes
    immediate: yes
    state: enabled
  become: yes

- name: create dir
  file:
    path: /var/ftp/pub/upload
    state: directory
    owner: ftp
    group: ftp
    mode: 0777

- name: copy template of vsftpd cfg
  template:
    src: vsftpd.conf.j2
    dest: /etc/vsftpd/vsftpd.conf
    owner: root
    group: root
    mode: '0600'

- name: enable vsftpd
  service:
    name: vsftpd
    enabled: yes
    state: restarted

- name: install semanage
  dnf:
    name: policycoreutils-python-utils
    state: latest

- name: SELinux add ftpd_anon_write
  seboolean:
    name: ftpd_anon_write
    state: yes
    persistent: yes

- name: SELinux add allow_ftpd_full_access
  seboolean:
    name: ftpd_full_access
    state: yes
    persistent: yes

- name: Apply SELinux rules
  command: restorecon -irv /var/ftp/pub/upload/