---
- name: create users
  hosts: node[1:2].example.com
  vars_files: secret.yml
        
  tasks:
  - name: creating users
    user:
      name: "{{ item.username }}"
      password: "{{ pwhash | password_hash('sha512') }}"
      comment: "{{ item.username }}@example.com"
      home: "/home/{{ item.username }}"
    loop:
      - username: alice
      - username: bob
      - username: carol
...