---
- name: modifying grub
  hosts: node[1:2].example.com
  user: ansible
  become: yes
  become_method: sudo
  become_user: root

  tasks:
  - name: change grub
    lineinfile:
      path: /etc/default/grub
      state: present
      backrefs: yes
      regexp: '^(GRUB_CMDLINE_LINUX=\")(crashkernel.*)'
      line: '\1net.ifnames=0 biosdevname=0 \2'
  
  - name: update grub
    command: grub2-mkconfig -o /boot/grub2/grub.cfg
...