---
- name: modifying grub
  hosts: node[1:2].example.com
  user: ansible
  become: yes
  become_method: sudo
  become_user: root

  tasks:
  - name: change grub
    lineinfile:
      # path: /etc/default/grub
      path: /home/ansible/grub
      state: present
      backrefs: yes
      regexp: '^(.*swap rhgb quiet)'
      line: '\1 net.ifnames=0 biosdevname=0"'   
...